import { PageLayout } from "#root/features/layout";
import Link from "next/link";
import { EffectorNext } from "@effector/next";
import "mvp.css";
import "../overrides.css";

import { ReduxDevToolsAdapter } from "#root/shared/redux-dev-tools-provider";
import { allSettled, fork, serialize } from 'effector'
import { cookies } from 'next/headers'
import { $counter } from '#root/features/async-counter/model'
import { breweriesPage } from '#root/page-content/breweries-list'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const scope = fork({values: new Map().set($counter, 42)});
  const values = serialize(scope);
  return (
    <html lang="en">
      <body>
        <ReduxDevToolsAdapter />
        <EffectorNext values={values}>
          <PageLayout>{children}</PageLayout>
        </EffectorNext>
      </body>
    </html>
  );
}
