import { PageLayout } from "#root/features/layout";
import Link from "next/link";
import { EffectorNext } from "@effector/next";
import "mvp.css";

import { ReduxDevToolsAdapter } from "#root/shared/redux-dev-tools-provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxDevToolsAdapter />
        <EffectorNext>
          <PageLayout>{children}</PageLayout>
        </EffectorNext>
      </body>
    </html>
  );
}
